# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'formRegGastos.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QDialog,
    QFrame, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTextEdit, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.setWindowModality(Qt.WindowModality.ApplicationModal)
        Dialog.resize(585, 460)
        Dialog.setModal(True)
        self.btnRegistrar = QPushButton(Dialog)
        self.btnRegistrar.setObjectName(u"btnRegistrar")
        self.btnRegistrar.setGeometry(QRect(20, 420, 251, 30))
        font = QFont()
        font.setFamilies([u"Comic Sans MS"])
        font.setPointSize(12)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setStyleSheet(u"background-color: rgb(8, 19, 95);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        icon = QIcon()
        icon.addFile(u"../iconos/guardar.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnRegistrar.setIcon(icon)
        self.btnRegistrar.setIconSize(QSize(40, 40))
        self.btnSalir = QPushButton(Dialog)
        self.btnSalir.setObjectName(u"btnSalir")
        self.btnSalir.setGeometry(QRect(310, 420, 251, 30))
        font1 = QFont()
        font1.setFamilies([u"Comic Sans MS"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.btnSalir.setFont(font1)
        self.btnSalir.setStyleSheet(u"background-color: rgb(8, 19, 95);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        icon1 = QIcon()
        icon1.addFile(u"../iconos/salir.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSalir.setIcon(icon1)
        self.btnSalir.setIconSize(QSize(30, 30))
        self.frame_5 = QFrame(Dialog)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 0, 641, 71))
        self.frame_5.setMaximumSize(QSize(16777215, 16777215))
        self.frame_5.setStyleSheet(u"background-color: rgb(8, 14, 91);")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.label_13 = QLabel(self.frame_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 40, 832, 31))
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.label_13.setFont(font2)
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(19, 39, 113);\n"
"color: rgb(255, 78, 2);\n"
"color: rgb(216, 224, 236);")
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.frame = QFrame(Dialog)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 70, 641, 331))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.cmbTipoGasto = QComboBox(self.frame)
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.addItem("")
        self.cmbTipoGasto.setObjectName(u"cmbTipoGasto")
        self.cmbTipoGasto.setGeometry(QRect(20, 180, 251, 30))
        self.cmbTipoGasto.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtDescripcion = QTextEdit(self.frame)
        self.txtDescripcion.setObjectName(u"txtDescripcion")
        self.txtDescripcion.setGeometry(QRect(310, 180, 251, 31))
        self.txtDescripcion.setStyleSheet(u"border-radius:5px;")
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 81, 16))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 250, 91, 16))
        self.boxDate = QDateEdit(self.frame)
        self.boxDate.setObjectName(u"boxDate")
        self.boxDate.setGeometry(QRect(150, 270, 121, 30))
        self.boxDate.setStyleSheet(u"border-radius:5px;")
        self.boxDate.setCalendarPopup(True)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(310, 160, 91, 16))
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(310, 250, 101, 16))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(170, 250, 81, 16))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 160, 111, 16))
        self.txtImporte = QLineEdit(self.frame)
        self.txtImporte.setObjectName(u"txtImporte")
        self.txtImporte.setGeometry(QRect(20, 270, 121, 30))
        self.txtImporte.setStyleSheet(u"border-radius:5px;")
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(480, 0, 101, 16))
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setPointSize(7)
        font3.setBold(True)
        font3.setItalic(True)
        self.label_3.setFont(font3)
        self.label_3.setStyleSheet(u"color: rgb(85, 0, 0);")
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(310, 20, 91, 16))
        self.cmbFormaPago = QComboBox(self.frame)
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.addItem("")
        self.cmbFormaPago.setObjectName(u"cmbFormaPago")
        self.cmbFormaPago.setGeometry(QRect(310, 40, 251, 30))
        self.cmbFormaPago.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.cmbProveedor = QComboBox(self.frame)
        self.cmbProveedor.addItem("")
        self.cmbProveedor.setObjectName(u"cmbProveedor")
        self.cmbProveedor.setGeometry(QRect(20, 40, 251, 30))
        self.cmbProveedor.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtIVA_ret = QLineEdit(self.frame)
        self.txtIVA_ret.setObjectName(u"txtIVA_ret")
        self.txtIVA_ret.setGeometry(QRect(310, 270, 121, 30))
        self.txtIVA_ret.setStyleSheet(u"border-radius:5px;")
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(440, 250, 101, 16))
        self.txtISR_ret = QLineEdit(self.frame)
        self.txtISR_ret.setObjectName(u"txtISR_ret")
        self.txtISR_ret.setGeometry(QRect(440, 270, 121, 30))
        self.txtISR_ret.setStyleSheet(u"border-radius:5px;")
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 90, 91, 16))
        self.txtnFactura = QLineEdit(self.frame)
        self.txtnFactura.setObjectName(u"txtnFactura")
        self.txtnFactura.setGeometry(QRect(20, 110, 251, 30))
        self.txtnFactura.setStyleSheet(u"border-radius:5px;")
        self.txtn_cheque = QLineEdit(self.frame)
        self.txtn_cheque.setObjectName(u"txtn_cheque")
        self.txtn_cheque.setGeometry(QRect(310, 110, 251, 30))
        self.txtn_cheque.setStyleSheet(u"border-radius:5px;")
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(310, 90, 91, 16))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle("")
        self.btnRegistrar.setText(QCoreApplication.translate("Dialog", u"Guadar", None))
        self.btnSalir.setText(QCoreApplication.translate("Dialog", u"Salir", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u" REGISTRO GASTOS MENSUALES", None))
        self.cmbTipoGasto.setItemText(0, QCoreApplication.translate("Dialog", u"--selecciona una opcion--", None))
        self.cmbTipoGasto.setItemText(1, QCoreApplication.translate("Dialog", u"conservacion", None))
        self.cmbTipoGasto.setItemText(2, QCoreApplication.translate("Dialog", u"operacion", None))
        self.cmbTipoGasto.setItemText(3, QCoreApplication.translate("Dialog", u"administrativo", None))
        self.cmbTipoGasto.setItemText(4, QCoreApplication.translate("Dialog", u"nomina", None))
        self.cmbTipoGasto.setItemText(5, QCoreApplication.translate("Dialog", u"impuestos", None))
        self.cmbTipoGasto.setItemText(6, QCoreApplication.translate("Dialog", u"oficina", None))
        self.cmbTipoGasto.setItemText(7, QCoreApplication.translate("Dialog", u"seguridad social (IMSS)", None))
        self.cmbTipoGasto.setItemText(8, QCoreApplication.translate("Dialog", u"asamblea", None))
        self.cmbTipoGasto.setItemText(9, QCoreApplication.translate("Dialog", u"comite", None))
        self.cmbTipoGasto.setItemText(10, QCoreApplication.translate("Dialog", u"no deducible", None))
        self.cmbTipoGasto.setItemText(11, QCoreApplication.translate("Dialog", u"extraordinario", None))
        self.cmbTipoGasto.setItemText(12, QCoreApplication.translate("Dialog", u"financiero", None))
        self.cmbTipoGasto.setItemText(13, QCoreApplication.translate("Dialog", u"estacionamiento", None))
        self.cmbTipoGasto.setItemText(14, QCoreApplication.translate("Dialog", u"publicidad", None))
        self.cmbTipoGasto.setItemText(15, QCoreApplication.translate("Dialog", u"eventos", None))
        self.cmbTipoGasto.setItemText(16, QCoreApplication.translate("Dialog", u"otro", None))

        self.label.setText(QCoreApplication.translate("Dialog", u"Proveedor*", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Importe Gasto*", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Concepto gasto", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"IVA retenido*", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Fecha Gasto*", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Tipo Gasto*", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"* campos obligatorios", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"Forma Pago *", None))
        self.cmbFormaPago.setItemText(0, QCoreApplication.translate("Dialog", u"--selecciona una opcion--", None))
        self.cmbFormaPago.setItemText(1, QCoreApplication.translate("Dialog", u"Transferencia SPEI", None))
        self.cmbFormaPago.setItemText(2, QCoreApplication.translate("Dialog", u"Efectivo", None))
        self.cmbFormaPago.setItemText(3, QCoreApplication.translate("Dialog", u"Cheque", None))
        self.cmbFormaPago.setItemText(4, QCoreApplication.translate("Dialog", u"Deposito Banco", None))
        self.cmbFormaPago.setItemText(5, QCoreApplication.translate("Dialog", u"Transferencia Interna", None))

        self.cmbProveedor.setItemText(0, QCoreApplication.translate("Dialog", u"--selecciona una opcion--", None))

        self.label_14.setText(QCoreApplication.translate("Dialog", u"ISR retenido*", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"Num. Factura", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Num. cheque", None))
    # retranslateUi

