# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'formMain.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QToolButton, QWidget)

class Ui_formMain(object):
    def setupUi(self, formMain):
        if not formMain.objectName():
            formMain.setObjectName(u"formMain")
        formMain.setWindowModality(Qt.WindowModality.NonModal)
        formMain.resize(1132, 805)
        formMain.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        formMain.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        formMain.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.actionRegMovCM = QAction(formMain)
        self.actionRegMovCM.setObjectName(u"actionRegMovCM")
        font = QFont()
        self.actionRegMovCM.setFont(font)
        self.actionAltaLocal = QAction(formMain)
        self.actionAltaLocal.setObjectName(u"actionAltaLocal")
        self.actionRegMovAC = QAction(formMain)
        self.actionRegMovAC.setObjectName(u"actionRegMovAC")
        self.actionAltaAC = QAction(formMain)
        self.actionAltaAC.setObjectName(u"actionAltaAC")
        self.actionRegContrato = QAction(formMain)
        self.actionRegContrato.setObjectName(u"actionRegContrato")
        self.actionReporte_Gastos = QAction(formMain)
        self.actionReporte_Gastos.setObjectName(u"actionReporte_Gastos")
        self.actionRegistro_O_Ingresos = QAction(formMain)
        self.actionRegistro_O_Ingresos.setObjectName(u"actionRegistro_O_Ingresos")
        self.actionReporte_Ingresos = QAction(formMain)
        self.actionReporte_Ingresos.setObjectName(u"actionReporte_Ingresos")
        self.actionCartera_Cuotas_Mantto = QAction(formMain)
        self.actionCartera_Cuotas_Mantto.setObjectName(u"actionCartera_Cuotas_Mantto")
        self.actionCartera_Areas_Comunes = QAction(formMain)
        self.actionCartera_Areas_Comunes.setObjectName(u"actionCartera_Areas_Comunes")
        self.actionDashboard_Gastos = QAction(formMain)
        self.actionDashboard_Gastos.setObjectName(u"actionDashboard_Gastos")
        self.actionDashboard_Ingresos = QAction(formMain)
        self.actionDashboard_Ingresos.setObjectName(u"actionDashboard_Ingresos")
        self.actionDasboard_Cartera_CM = QAction(formMain)
        self.actionDasboard_Cartera_CM.setObjectName(u"actionDasboard_Cartera_CM")
        self.actionDasboard_Cartera_AC = QAction(formMain)
        self.actionDasboard_Cartera_AC.setObjectName(u"actionDasboard_Cartera_AC")
        self.actionNuevo_Usuario = QAction(formMain)
        self.actionNuevo_Usuario.setObjectName(u"actionNuevo_Usuario")
        self.actionCambiar_Usuario = QAction(formMain)
        self.actionCambiar_Usuario.setObjectName(u"actionCambiar_Usuario")
        self.actionRegistro_Empresa = QAction(formMain)
        self.actionRegistro_Empresa.setObjectName(u"actionRegistro_Empresa")
        self.actionRegistro_Proveedor = QAction(formMain)
        self.actionRegistro_Proveedor.setObjectName(u"actionRegistro_Proveedor")
        self.actionRegistro_Empleado = QAction(formMain)
        self.actionRegistro_Empleado.setObjectName(u"actionRegistro_Empleado")
        self.actionContacto = QAction(formMain)
        self.actionContacto.setObjectName(u"actionContacto")
        self.actionManuales = QAction(formMain)
        self.actionManuales.setObjectName(u"actionManuales")
        self.actionRegistrar_Cliente = QAction(formMain)
        self.actionRegistrar_Cliente.setObjectName(u"actionRegistrar_Cliente")
        self.actionAlta_Proveedor = QAction(formMain)
        self.actionAlta_Proveedor.setObjectName(u"actionAlta_Proveedor")
        self.actionEditar = QAction(formMain)
        self.actionEditar.setObjectName(u"actionEditar")
        self.actionRegistrar_cliente = QAction(formMain)
        self.actionRegistrar_cliente.setObjectName(u"actionRegistrar_cliente")
        self.actionRegistrar_Gastos = QAction(formMain)
        self.actionRegistrar_Gastos.setObjectName(u"actionRegistrar_Gastos")
        self.actionAlta_Prest_Serv = QAction(formMain)
        self.actionAlta_Prest_Serv.setObjectName(u"actionAlta_Prest_Serv")
        self.actionAlta_Empleado = QAction(formMain)
        self.actionAlta_Empleado.setObjectName(u"actionAlta_Empleado")
        self.actionFacturacion_Masiva = QAction(formMain)
        self.actionFacturacion_Masiva.setObjectName(u"actionFacturacion_Masiva")
        self.actionLocales_Comerciales = QAction(formMain)
        self.actionLocales_Comerciales.setObjectName(u"actionLocales_Comerciales")
        self.actionAreas_Comunes = QAction(formMain)
        self.actionAreas_Comunes.setObjectName(u"actionAreas_Comunes")
        self.actionRegistrar_Empresa = QAction(formMain)
        self.actionRegistrar_Empresa.setObjectName(u"actionRegistrar_Empresa")
        self.actionCambiar_usuario = QAction(formMain)
        self.actionCambiar_usuario.setObjectName(u"actionCambiar_usuario")
        self.actionCarga_Clientes = QAction(formMain)
        self.actionCarga_Clientes.setObjectName(u"actionCarga_Clientes")
        self.actionCarga_Locales = QAction(formMain)
        self.actionCarga_Locales.setObjectName(u"actionCarga_Locales")
        self.actionCarga_Areas_Comunes = QAction(formMain)
        self.actionCarga_Areas_Comunes.setObjectName(u"actionCarga_Areas_Comunes")
        self.actionCarga_Contratos = QAction(formMain)
        self.actionCarga_Contratos.setObjectName(u"actionCarga_Contratos")
        self.actionCarga_Saldos_Iniciales = QAction(formMain)
        self.actionCarga_Saldos_Iniciales.setObjectName(u"actionCarga_Saldos_Iniciales")
        self.actionRegCuentas = QAction(formMain)
        self.actionRegCuentas.setObjectName(u"actionRegCuentas")
        self.actionBuscar_Contratos = QAction(formMain)
        self.actionBuscar_Contratos.setObjectName(u"actionBuscar_Contratos")
        self.centralwidget = QWidget(formMain)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(245, 245, 252);")
        self.lblImagen = QLabel(self.centralwidget)
        self.lblImagen.setObjectName(u"lblImagen")
        self.lblImagen.setGeometry(QRect(9, 9, 680, 695))
        self.lblImagen.setPixmap(QPixmap(u"../imagenes/financier.png"))
        self.lblImagen.setScaledContents(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-60, 710, 1231, 51))
        font1 = QFont()
        font1.setFamilies([u"Goudy Old Style"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"background-color: rgb(19, 39, 113);\n"
"color: rgb(255, 255, 255);")
        self.label.setFrameShadow(QFrame.Shadow.Sunken)
        self.label.setMidLineWidth(1)
        self.label.setTextFormat(Qt.TextFormat.RichText)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame1 = QFrame(self.centralwidget)
        self.frame1.setObjectName(u"frame1")
        self.frame1.setGeometry(QRect(680, 10, 531, 690))
        self.frame1.setStyleSheet(u"")
        self.frame1.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QFrame.Shadow.Raised)
        self.txtUsuario = QLineEdit(self.frame1)
        self.txtUsuario.setObjectName(u"txtUsuario")
        self.txtUsuario.setGeometry(QRect(110, 310, 250, 30))
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(10)
        font2.setBold(False)
        self.txtUsuario.setFont(font2)
        self.txtUsuario.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtUsuario.setCursorPosition(0)
        self.txtUsuario.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.txtPassword = QLineEdit(self.frame1)
        self.txtPassword.setObjectName(u"txtPassword")
        self.txtPassword.setGeometry(QRect(110, 370, 250, 30))
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setPointSize(10)
        self.txtPassword.setFont(font3)
        self.txtPassword.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.txtPassword.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtPassword.setEchoMode(QLineEdit.EchoMode.Password)
        self.txtPassword.setCursorPosition(0)
        self.txtPassword.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btnEntrar = QPushButton(self.frame1)
        self.btnEntrar.setObjectName(u"btnEntrar")
        self.btnEntrar.setGeometry(QRect(110, 440, 250, 31))
        font4 = QFont()
        font4.setFamilies([u"Comic Sans MS"])
        font4.setPointSize(11)
        font4.setBold(True)
        self.btnEntrar.setFont(font4)
        self.btnEntrar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnEntrar.setStyleSheet(u"background-color: rgb(0, 94, 242);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btnRegresar = QPushButton(self.frame1)
        self.btnRegresar.setObjectName(u"btnRegresar")
        self.btnRegresar.setGeometry(QRect(110, 560, 250, 21))
        font5 = QFont()
        font5.setFamilies([u"Comic Sans MS"])
        font5.setPointSize(10)
        font5.setBold(True)
        self.btnRegresar.setFont(font5)
        self.btnRegresar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnRegresar.setStyleSheet(u"background-color: rgb(0, 94, 242);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btnNewUser = QPushButton(self.frame1)
        self.btnNewUser.setObjectName(u"btnNewUser")
        self.btnNewUser.setGeometry(QRect(110, 490, 250, 30))
        self.btnNewUser.setFont(font4)
        self.btnNewUser.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnNewUser.setStyleSheet(u"background-color: rgb(0, 94, 242);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtNameUser = QLineEdit(self.frame1)
        self.txtNameUser.setObjectName(u"txtNameUser")
        self.txtNameUser.setGeometry(QRect(110, 240, 250, 30))
        self.txtNameUser.setFont(font2)
        self.txtNameUser.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.txtNameUser.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius:5px;")
        self.txtNameUser.setCursorPosition(0)
        self.txtNameUser.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.txtNameUser.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)
        self.lblRecPassword = QLabel(self.frame1)
        self.lblRecPassword.setObjectName(u"lblRecPassword")
        self.lblRecPassword.setGeometry(QRect(130, 410, 211, 20))
        font6 = QFont()
        font6.setFamilies([u"Comic Sans MS"])
        font6.setItalic(True)
        font6.setUnderline(False)
        self.lblRecPassword.setFont(font6)
        self.lblRecPassword.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.lblRecPassword.setStyleSheet(u"color: rgb(255, 78, 2);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));")
        self.lblRecPassword.setFrameShadow(QFrame.Shadow.Plain)
        self.lblRecPassword.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblRecPassword.setOpenExternalLinks(False)
        self.btnRecuperar = QPushButton(self.frame1)
        self.btnRecuperar.setObjectName(u"btnRecuperar")
        self.btnRecuperar.setGeometry(QRect(110, 610, 250, 31))
        self.btnRecuperar.setFont(font4)
        self.btnRecuperar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnRecuperar.setStyleSheet(u"background-color: rgb(0, 94, 242);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.btnRecuperar.setFlat(False)
        self.btnInvisible = QPushButton(self.frame1)
        self.btnInvisible.setObjectName(u"btnInvisible")
        self.btnInvisible.setGeometry(QRect(170, 640, 131, 31))
        self.btnInvisible.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnInvisible.setStyleSheet(u"background-color: rgb(245, 245, 252);\n"
"")
        self.btnInvisible.setAutoDefault(False)
        self.btnInvisible.setFlat(False)
        self.label_2 = QLabel(self.frame1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(170, 70, 121, 101))
        self.label_2.setPixmap(QPixmap(u"../iconos/Oxygen-Icons.org-Oxygen-Apps-preferences-system-login.256.png"))
        self.label_2.setScaledContents(True)
        self.toolButton = QToolButton(self.frame1)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(365, 375, 22, 22))
        self.btnCambiarUsuario = QPushButton(self.frame1)
        self.btnCambiarUsuario.setObjectName(u"btnCambiarUsuario")
        self.btnCambiarUsuario.setGeometry(QRect(110, 530, 250, 21))
        self.btnCambiarUsuario.setFont(font5)
        self.btnCambiarUsuario.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnCambiarUsuario.setStyleSheet(u"background-color: rgb(0, 94, 242);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.txtUsuario.raise_()
        self.txtPassword.raise_()
        self.btnEntrar.raise_()
        self.btnRegresar.raise_()
        self.btnNewUser.raise_()
        self.txtNameUser.raise_()
        self.btnRecuperar.raise_()
        self.lblRecPassword.raise_()
        self.btnInvisible.raise_()
        self.label_2.raise_()
        self.toolButton.raise_()
        self.btnCambiarUsuario.raise_()
        self.btnIngresar = QPushButton(self.centralwidget)
        self.btnIngresar.setObjectName(u"btnIngresar")
        self.btnIngresar.setGeometry(QRect(10, 10, 91, 61))
        self.btnIngresar.setFont(font5)
        self.btnIngresar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnIngresar.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        icon = QIcon()
        icon.addFile(u"../iconos/Webiconset-Application-Register.128 (1).png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnIngresar.setIcon(icon)
        self.btnIngresar.setIconSize(QSize(50, 50))
        self.btnSalirPP = QPushButton(self.centralwidget)
        self.btnSalirPP.setObjectName(u"btnSalirPP")
        self.btnSalirPP.setGeometry(QRect(1070, 660, 61, 45))
        font7 = QFont()
        font7.setFamilies([u"Comic Sans MS"])
        font7.setPointSize(8)
        font7.setBold(True)
        self.btnSalirPP.setFont(font7)
        self.btnSalirPP.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnSalirPP.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.btnSalirPP.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        icon1 = QIcon()
        icon1.addFile(u"../iconos/eliminar.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btnSalirPP.setIcon(icon1)
        self.btnSalirPP.setIconSize(QSize(50, 50))
        self.btnSalirPP.setFlat(False)
        self.lblName_User = QLabel(self.centralwidget)
        self.lblName_User.setObjectName(u"lblName_User")
        self.lblName_User.setGeometry(QRect(5, 690, 161, 20))
        font8 = QFont()
        font8.setFamilies([u"Comic Sans MS"])
        font8.setPointSize(9)
        self.lblName_User.setFont(font8)
        self.lblName_User.setStyleSheet(u"color: rgb(255, 78, 2);")
        self.lblName_User.setAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft)
        self.lblName_User.setIndent(0)
        formMain.setCentralWidget(self.centralwidget)
        self.frame1.raise_()
        self.lblImagen.raise_()
        self.label.raise_()
        self.btnIngresar.raise_()
        self.btnSalirPP.raise_()
        self.lblName_User.raise_()
        self.menubar = QMenuBar(formMain)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1132, 24))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        font9 = QFont()
        font9.setFamilies([u"Goudy Old Style"])
        font9.setPointSize(12)
        font9.setBold(True)
        self.menubar.setFont(font9)
        self.menubar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.menubar.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.menubar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.menubar.setStyleSheet(u"background-color: rgb(7, 12, 88);\n"
"\n"
"color: rgb(255, 255, 255);")
        self.menuLocales_Comerciales = QMenu(self.menubar)
        self.menuLocales_Comerciales.setObjectName(u"menuLocales_Comerciales")
        self.menuAreas_comunes = QMenu(self.menubar)
        self.menuAreas_comunes.setObjectName(u"menuAreas_comunes")
        self.menuFacturacion = QMenu(self.menubar)
        self.menuFacturacion.setObjectName(u"menuFacturacion")
        self.menuActualizar_Cuotas = QMenu(self.menubar)
        self.menuActualizar_Cuotas.setObjectName(u"menuActualizar_Cuotas")
        self.menuGastos_Egresos = QMenu(self.menubar)
        self.menuGastos_Egresos.setObjectName(u"menuGastos_Egresos")
        self.menuOtros_Ingresos = QMenu(self.menubar)
        self.menuOtros_Ingresos.setObjectName(u"menuOtros_Ingresos")
        self.menuCartera_Cobranza = QMenu(self.menubar)
        self.menuCartera_Cobranza.setObjectName(u"menuCartera_Cobranza")
        self.menuEstadisticas_y_Graficos = QMenu(self.menubar)
        self.menuEstadisticas_y_Graficos.setObjectName(u"menuEstadisticas_y_Graficos")
        self.menuAyuda = QMenu(self.menubar)
        self.menuAyuda.setObjectName(u"menuAyuda")
        self.menuConfiguracion = QMenu(self.menubar)
        self.menuConfiguracion.setObjectName(u"menuConfiguracion")
        formMain.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(formMain)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setMaximumSize(QSize(16777215, 16777213))
        font10 = QFont()
        font10.setFamilies([u"Comic Sans MS"])
        self.statusBar.setFont(font10)
        self.statusBar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        formMain.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menuLocales_Comerciales.menuAction())
        self.menubar.addAction(self.menuAreas_comunes.menuAction())
        self.menubar.addAction(self.menuFacturacion.menuAction())
        self.menubar.addAction(self.menuActualizar_Cuotas.menuAction())
        self.menubar.addAction(self.menuGastos_Egresos.menuAction())
        self.menubar.addAction(self.menuOtros_Ingresos.menuAction())
        self.menubar.addAction(self.menuCartera_Cobranza.menuAction())
        self.menubar.addAction(self.menuEstadisticas_y_Graficos.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.menuLocales_Comerciales.addAction(self.actionRegMovCM)
        self.menuLocales_Comerciales.addAction(self.actionAltaLocal)
        self.menuAreas_comunes.addAction(self.actionRegMovAC)
        self.menuAreas_comunes.addAction(self.actionAltaAC)
        self.menuAreas_comunes.addAction(self.actionRegContrato)
        self.menuAreas_comunes.addAction(self.actionBuscar_Contratos)
        self.menuFacturacion.addAction(self.actionRegistrar_cliente)
        self.menuFacturacion.addAction(self.actionFacturacion_Masiva)
        self.menuFacturacion.addSeparator()
        self.menuActualizar_Cuotas.addAction(self.actionLocales_Comerciales)
        self.menuActualizar_Cuotas.addAction(self.actionAreas_Comunes)
        self.menuGastos_Egresos.addAction(self.actionRegistrar_Gastos)
        self.menuGastos_Egresos.addAction(self.actionReporte_Gastos)
        self.menuGastos_Egresos.addAction(self.actionAlta_Prest_Serv)
        self.menuGastos_Egresos.addAction(self.actionAlta_Empleado)
        self.menuOtros_Ingresos.addAction(self.actionReporte_Ingresos)
        self.menuOtros_Ingresos.addAction(self.actionRegistro_O_Ingresos)
        self.menuCartera_Cobranza.addAction(self.actionCartera_Cuotas_Mantto)
        self.menuCartera_Cobranza.addAction(self.actionCartera_Areas_Comunes)
        self.menuEstadisticas_y_Graficos.addAction(self.actionDashboard_Ingresos)
        self.menuEstadisticas_y_Graficos.addAction(self.actionDashboard_Gastos)
        self.menuEstadisticas_y_Graficos.addAction(self.actionDasboard_Cartera_CM)
        self.menuEstadisticas_y_Graficos.addAction(self.actionDasboard_Cartera_AC)
        self.menuAyuda.addAction(self.actionContacto)
        self.menuAyuda.addAction(self.actionManuales)
        self.menuConfiguracion.addAction(self.actionCarga_Locales)
        self.menuConfiguracion.addAction(self.actionCarga_Areas_Comunes)
        self.menuConfiguracion.addAction(self.actionCarga_Clientes)
        self.menuConfiguracion.addAction(self.actionCarga_Contratos)
        self.menuConfiguracion.addAction(self.actionCarga_Saldos_Iniciales)
        self.menuConfiguracion.addAction(self.actionRegCuentas)

        self.retranslateUi(formMain)

        QMetaObject.connectSlotsByName(formMain)
    # setupUi

    def retranslateUi(self, formMain):
        formMain.setWindowTitle("")
        self.actionRegMovCM.setText(QCoreApplication.translate("formMain", u"Reg. Movimientos CM", None))
#if QT_CONFIG(shortcut)
        self.actionRegMovCM.setShortcut(QCoreApplication.translate("formMain", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionAltaLocal.setText(QCoreApplication.translate("formMain", u"Alta Local Comercial", None))
        self.actionRegMovAC.setText(QCoreApplication.translate("formMain", u"Reg. Movimientos AC", None))
#if QT_CONFIG(shortcut)
        self.actionRegMovAC.setShortcut(QCoreApplication.translate("formMain", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionAltaAC.setText(QCoreApplication.translate("formMain", u"Alta Area Comun", None))
        self.actionRegContrato.setText(QCoreApplication.translate("formMain", u"Registrar Contrato", None))
        self.actionReporte_Gastos.setText(QCoreApplication.translate("formMain", u"Reporte Gastos", None))
        self.actionRegistro_O_Ingresos.setText(QCoreApplication.translate("formMain", u"Registro otros Ingresos", None))
        self.actionReporte_Ingresos.setText(QCoreApplication.translate("formMain", u"Reporte Ingresos", None))
        self.actionCartera_Cuotas_Mantto.setText(QCoreApplication.translate("formMain", u"Cuotas Locales Comerciales", None))
        self.actionCartera_Areas_Comunes.setText(QCoreApplication.translate("formMain", u"Cuotas Areas Comunes", None))
        self.actionDashboard_Gastos.setText(QCoreApplication.translate("formMain", u"Dashboard Gastos", None))
        self.actionDashboard_Ingresos.setText(QCoreApplication.translate("formMain", u"Dashboard Ingresos", None))
        self.actionDasboard_Cartera_CM.setText(QCoreApplication.translate("formMain", u"Dasboard Cartera Locales", None))
        self.actionDasboard_Cartera_AC.setText(QCoreApplication.translate("formMain", u"Dasboard Cartera Areas", None))
        self.actionNuevo_Usuario.setText(QCoreApplication.translate("formMain", u"Nuevo Usuario", None))
        self.actionCambiar_Usuario.setText(QCoreApplication.translate("formMain", u"Cambiar Usuario", None))
        self.actionRegistro_Empresa.setText(QCoreApplication.translate("formMain", u"Registro Empresa", None))
        self.actionRegistro_Proveedor.setText(QCoreApplication.translate("formMain", u"Registro Proveedor", None))
        self.actionRegistro_Empleado.setText(QCoreApplication.translate("formMain", u"Registro Empleado", None))
        self.actionContacto.setText(QCoreApplication.translate("formMain", u"Contacto", None))
        self.actionManuales.setText(QCoreApplication.translate("formMain", u"Manuales", None))
        self.actionRegistrar_Cliente.setText(QCoreApplication.translate("formMain", u"Registrar Cliente", None))
        self.actionAlta_Proveedor.setText(QCoreApplication.translate("formMain", u"Alta Proveedor", None))
        self.actionEditar.setText(QCoreApplication.translate("formMain", u"Editar", None))
        self.actionRegistrar_cliente.setText(QCoreApplication.translate("formMain", u"Registrar Cliente", None))
        self.actionRegistrar_Gastos.setText(QCoreApplication.translate("formMain", u"Registro de Gastos", None))
        self.actionAlta_Prest_Serv.setText(QCoreApplication.translate("formMain", u"Reg Prestador Servicios", None))
        self.actionAlta_Empleado.setText(QCoreApplication.translate("formMain", u"Reg Empleados", None))
        self.actionFacturacion_Masiva.setText(QCoreApplication.translate("formMain", u"Facturacion Masiva", None))
        self.actionLocales_Comerciales.setText(QCoreApplication.translate("formMain", u"Locales Comerciales", None))
        self.actionAreas_Comunes.setText(QCoreApplication.translate("formMain", u"Areas Comunes", None))
        self.actionRegistrar_Empresa.setText(QCoreApplication.translate("formMain", u"Registrar Empresa", None))
        self.actionCambiar_usuario.setText(QCoreApplication.translate("formMain", u"Cambiar Usuario", None))
        self.actionCarga_Clientes.setText(QCoreApplication.translate("formMain", u"Carga Clientes", None))
        self.actionCarga_Locales.setText(QCoreApplication.translate("formMain", u"Carga Locales", None))
        self.actionCarga_Areas_Comunes.setText(QCoreApplication.translate("formMain", u"Carga Areas Comunes", None))
        self.actionCarga_Contratos.setText(QCoreApplication.translate("formMain", u"Carga Contratos", None))
        self.actionCarga_Saldos_Iniciales.setText(QCoreApplication.translate("formMain", u"Carga Saldos Iniciales", None))
        self.actionRegCuentas.setText(QCoreApplication.translate("formMain", u"Cuentas Bancarias", None))
        self.actionBuscar_Contratos.setText(QCoreApplication.translate("formMain", u"Buscar Contratos", None))
        self.lblImagen.setText("")
        self.label.setText(QCoreApplication.translate("formMain", u"GESTOR ADMINISTRATIVO CONDOMINAL ", None))
        self.txtUsuario.setText("")
        self.txtUsuario.setPlaceholderText(QCoreApplication.translate("formMain", u"Captura Usuario", None))
        self.txtPassword.setText("")
        self.txtPassword.setPlaceholderText(QCoreApplication.translate("formMain", u"Captura Contrase\u00f1a", None))
        self.btnEntrar.setText(QCoreApplication.translate("formMain", u"Entrar", None))
        self.btnRegresar.setText(QCoreApplication.translate("formMain", u"Regresar", None))
        self.btnNewUser.setText(QCoreApplication.translate("formMain", u"Nuevo Usuario", None))
        self.txtNameUser.setText("")
        self.txtNameUser.setPlaceholderText(QCoreApplication.translate("formMain", u"Captura Nombre Usuario", None))
        self.lblRecPassword.setText(QCoreApplication.translate("formMain", u"Recuperar Contrase\u00f1a", None))
        self.btnRecuperar.setText(QCoreApplication.translate("formMain", u"Recuperar", None))
        self.btnInvisible.setText("")
        self.label_2.setText("")
        self.toolButton.setText(QCoreApplication.translate("formMain", u"...", None))
        self.btnCambiarUsuario.setText(QCoreApplication.translate("formMain", u"Cambiar Usuario", None))
#if QT_CONFIG(tooltip)
        self.btnIngresar.setToolTip(QCoreApplication.translate("formMain", u"<html><head/><body><p><span style=\" font-size:12pt; color:#010223;\">Ingresar Sistema</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnIngresar.setText("")
#if QT_CONFIG(tooltip)
        self.btnSalirPP.setToolTip(QCoreApplication.translate("formMain", u"<html><head/><body><p><span style=\" font-size:12pt; color:#010223;\">Salir Sistema</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnSalirPP.setText("")
        self.lblName_User.setText("")
        self.menuLocales_Comerciales.setTitle(QCoreApplication.translate("formMain", u"Locales Comerciales", None))
        self.menuAreas_comunes.setTitle(QCoreApplication.translate("formMain", u"Areas comunes", None))
        self.menuFacturacion.setTitle(QCoreApplication.translate("formMain", u"Facturacion", None))
        self.menuActualizar_Cuotas.setTitle(QCoreApplication.translate("formMain", u"Actualizar Cuotas", None))
        self.menuGastos_Egresos.setTitle(QCoreApplication.translate("formMain", u"Gastos", None))
        self.menuOtros_Ingresos.setTitle(QCoreApplication.translate("formMain", u"Otros Ingresos", None))
        self.menuCartera_Cobranza.setTitle(QCoreApplication.translate("formMain", u"Cartera Cobranza", None))
        self.menuEstadisticas_y_Graficos.setTitle(QCoreApplication.translate("formMain", u"Estadisticas y Graficos", None))
        self.menuAyuda.setTitle(QCoreApplication.translate("formMain", u"Ayuda", None))
        self.menuConfiguracion.setTitle(QCoreApplication.translate("formMain", u"Configuracion", None))
    # retranslateUi

